<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->partial('inc.head.phtml'); ?>
    </head>
    <body>
        <?php echo $this->action('success', 'registration', 'users'); ?>
        <section id="body">
            <?php echo $this->partial('inc.header.phtml'); ?>
            <div class="clear">&nbsp;</div>

            <section id="content"><!--content-->
                <div class="wrapper">
                    <aside id="left-col">
                        <?php echo $this->action('leftuserpanel', 'index', 'users'); ?>
                        <div id="leftHelp">
                            <p>Заполните все поля, чтобы опубликовать вопрос.</p>
                            <p>Вы можете ваш вопрос платным. Вы сами определяете стоимость  вопроса.</p>
                            <p class="strong">Чем больше стоимость, тем больше внимания будет к вашему вопросу.</p>
                        </div>
                        <div id="offers">
                            <h2>Предлагаю услуги:</h2>
                            <dl>
                                <dt><img src="design/images/offers.jpg" alt=""></dt>
                                <dd class="name">Иванов Иван Сергеевич</dd>
                                <dd class="spec">Специалист по гражданскому и семейному праву</dd>
                                <dd><input type="submit" class="button-fox" value="Написать"></dd>
                                <dd class="clear none">&nbsp;</dd>
                            </dl>
                            <dl>
                                <dt><img src="design/images/offers.jpg" alt=""></dt>
                                <dd class="name">Иванов Иван Сергеевич</dd>
                                <dd class="spec">Специалист по гражданскому и семейному праву</dd>
                                <dd><input type="submit" class="button-fox" value="Написать"></dd>
                                <dd class="clear none">&nbsp;</dd>
                            </dl>
                            <dl>
                                <dt><img src="design/images/offers.jpg" alt=""></dt>
                                <dd class="name">Иванов Иван Сергеевич</dd>
                                <dd class="spec">Специалист по гражданскому и семейному праву</dd>
                                <dd><input type="submit" class="button-fox" value="Написать"></dd>
                                <dd class="clear none">&nbsp;</dd>
                            </dl>
                        </div>
                    </aside>
                    <section id="right-col">
                        <?php echo $this->layout()->content; ?>
                    </section>
                </div>
            </section><!--/content-->

            <div class="clear">&nbsp;</div>
            <div id="rasporka"></div>

        </section><!--/body-wrapper-->

        <?php echo $this->partial('inc.footer.phtml'); ?>
    </body>
</html>