<?php if ($this->auth->hasIdentity()) { ?>
    <div id="user">
        <img src="/design/img/noAvatar.png" alt="">
        <p class="name"><?php echo $this->auth->getIdentity()->name; ?></p>
        <a class="editProfile" href="<?php echo Rastor_Url::get('profile_edit'); ?>">редактировать профиль</a>
        <p class="myMessages"><a href="">Мои сообщения</a> (<span>3</span>)</p>
    </div>
<?php } else { ?>
    <div id="userRegister">
        <a href="<?php echo Rastor_Url::get('registration'); ?>">
            Зарегистрироваться »<br>
            <span>и задать вопрос</span>
        </a>
    </div>
<?php } ?>