<?php //echo $this->form;     ?>
<form id="questionForm" method="post">
    <dl>
        <?php echo $this->form->name; ?>
        <?php echo $this->form->content; ?>
        <dt>
        Тема вопроса:
        <span>Укажите тему: это поможет найти специалистов для вашей ситуации</span>
        </dt>
        <dd>
            <div class="field first">
                <ul>
                    <li>
                        <input type="radio" name="type" value="0" id="question-privat" >
                        <label for="question-privat" class="caption">Частный вопрос</label>
                    </li>
                    <li>
                        <input type="radio" name="type" value="1" id="question-juridical">
                        <label for="question-juridical" class="caption">Вопрос о бизнесе</label>
                    </li>
                </ul>
            </div>
            <div id="selectionChoose" class="selectionChoose">
                <div class="head">
                    «&nbsp;<a href="" class="backlink">Назад</a>
                </div>
                <div class="body first">
                    <ul>
                        <?php foreach ($this->tags1 as $tag) { ?>
                            <li>
                                <input type="checkbox" name="tag_<?php echo $tag->id; ?>" id="checkbox_<?php echo $tag->id; ?>">
                                <label for="tag_<?php echo $tag->id; ?>"><?php echo $tag->name; ?></label>
                                <p class="description"><?php echo $tag->categories; ?></p>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="body second">
                    <ul>
                        <?php foreach ($this->tags2 as $tag) { ?>
                            <li>
                                <input type="checkbox" name="tag_<?php echo $tag->id; ?>" id="checkbox_<?php echo $tag->id; ?>">
                                <label for="tag_<?php echo $tag->id; ?>"><?php echo $tag->name; ?></label>
                                <p class="description"><?php echo $tag->categories; ?></p>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </dd>
        <?php echo $this->form->paid; ?>
        <div class="paidBlock">
            <dt>Стоимость вопроса:</dt>
            <dd>
                <div class="question-amount">
                    <div class="slider1"></div>
                    <?php echo $this->form->price; ?>
                    <p>рублей</p>
                    <ul>
                        <li class="easy">Простой вопрос</li>
                        <li class="normal">Обычный вопрос</li>
                        <li class="hard">Сложный вопрос</li>
                    </ul>
                </div>
            </dd>
        </div>
        <?php echo $this->form->user_name; ?>
        <?php echo $this->form->user_email; ?>
        <?php echo $this->form->city_id; ?>
    </dl>
    <div class="buttonHolder">
        <input type="submit" class="buttonClear" value="Очистить">
        <input type="submit" class="buttonSendQuestion" value="Отправить вопрос">
    </div>
</form>
<script type="text/javascript">
    $(document).ready(function(){
        $( ".question-amount .slider1").slider({
            value: <?php echo $this->form->price->getValue() ? $this->form->price->getValue() : 90; ?>,
            min: 90,
            max: 15000,
            step: 10,
            slide: function( event, ui ) {
                $(".question-amount .amount1").val(ui.value);
            }
        });
        $(".question-amount .amount1" ).val($(".question-amount .slider1").slider("value"));
        
        $('#questionForm .selectionChoose').hide();
        $('#questionForm .selectionChoose .body').hide();
        if ($('#questionForm input[name=paid]').val() == '0') {
            $('#questionForm .paidBlock').hide();
        }
        
        $('#questionForm input[name=type]').change(function(){
            $('#questionForm .field.first').hide();
            $('#questionForm .selectionChoose').show();
            if ($(this).val() == '0') {
                $('#questionForm .selectionChoose .body.first').show();
            } else {
                $('#questionForm .selectionChoose .body.second').show();
            }
        });
        
        $('#questionForm .backlink').click(function(){
            $('#questionForm .selectionChoose').hide();
            $('#questionForm .selectionChoose .body').hide();
            $('#questionForm .field.first').show();
            $('#questionForm input[name=type]').attr('checked', false);
            return false;
        });
        
        $('#questionForm input[name=paid]').change(function(){
            if ($('#questionForm input[name=paid]:checked').val() == 1) {
                $('#questionForm .paidBlock').show();
            } else {
                $('#questionForm .paidBlock').hide();
            }
        });
        
        $('#questionForm input[name=paid]').change();
    });
</script>