<div id="userIn">
    <div class="img"><img src="/design/images/faceHuge.jpg" alt=""></div>
    <p><?php echo $this->auth->getIdentity()->name; ?></p>
    <p class="myMessages"><a href="">Мои сообщения</a> (<span>3</span>)</p>
</div>
<div id="profile">
    <div class="profile">
        <ul>
            <li><a href="">Редактировать профиль</a>
                <ul>
                    <li class="active">Личная информация</li>
                    <li><a href="">Образование и работа</a></li>
                    <li><a href="">Контатная информация</a></li>
                    <li><a href="">Услуги</a></li>
                    <li><a href="">Настройка оповещений</a></li>
                    <li><a href="">Рекламная компания</a></li>
                </ul>
            </li>
            <li class="back"><a href="">Назад</a></li>
        </ul>
    </div>
    <div class="leftSay"></div>
</div>